# Generated by Django 5.2.8 on 2025-11-11 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_conversation_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
